"""add_pd_agreed_to_user

Revision ID: ee8bfa2056e2
Revises: 
Create Date: 2026-05-26 20:46:40.763595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee8bfa2056e2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Название категории'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False, comment='ID пользователя в Telegram'),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время регистрации'),
    sa.Column('last_activity', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Последняя активность'),
    sa.Column('pd_agreed', sa.Boolean(), nullable=False, comment='Согласие на обработку персональных данных'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False, comment='Название кейса'),
    sa.Column('solution', sa.Text(), nullable=False, comment='Пошаговое решение с ссылками на НПА'),
    sa.Column('category_id', sa.Integer(), nullable=False, comment='Категория'),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('russian', coalesce(title, '') || ' ' || coalesce(solution, ''))", persisted=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['case_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Пользователь'),
    sa.Column('message', sa.Text(), nullable=False, comment='Текст обращения'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время отправки'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False, comment='Название шаблона'),
    sa.Column('case_id', sa.Integer(), nullable=False, comment='Кейс'),
    sa.Column('file_id', sa.String(length=500), nullable=False, comment='Telegram file_id документа'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Пользователь'),
    sa.Column('case_id', sa.Integer(), nullable=False, comment='Кейс'),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время просмотра'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_requests')
    op.drop_table('documents')
    op.drop_table('feedback')
    op.drop_table('cases')
    op.drop_table('users')
    op.drop_table('case_categories')
    # ### end Alembic commands ###
